### ISSUE TITLE
Screenshots do not capture anything

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple-ssb-debugger#114]
Attempting to use the screenshot feature in the debugger successfully saves an image, but it results in a blank, transparent 256x384 image.

**Comment by theCapypara** [comment]
Can confirm under Linux, this is a general issue.

**Comment by theCapypara** [comment]
It seems like the image is actually there, it's just that the alpha channel is 0 for all pixels.

It seems that DeSmuME's display buffer now uses 0 for the (unused) alpha channel. Or maybe it always did and we just changed how it's read, don't quite remember. In any case, we will have to manually change the alpha value of all pixels.

**Comment by theCapypara** [comment]
turning off the alpha channel also reveals that some of the color channels are flipped.
![grafik](https://github.com/SkyTemple/skytemple-ssb-debugger/assets/3512122/3353caa1-e481-45bb-9d12-1151206f1a73)
