### ISSUE TITLE
Error with routine aliases (for targeted routines)

### ISSUE THREAD

**Issue by Adex-8x** [SkyTemple/skytemple-ssb-debugger#73]
Originally reported at: https://discord.com/channels/710190644152369162/712341699292037121/955919539307159633

While trying to load a new scene from the debugger, this error pops up and disallows savestates. When trying to close SkyTemple, it also hangs indefinitely.
For context, I had only added three new scenes and one new script (this particular one was the first new scene added). This error did not happen immediately, as it only started failing sometime after adding two new scenes.

**Comment by theCapypara** [comment]
This is the following issues in Sentry:
- SKYTEMPLE-5C
- SKYTEMPLE-5D
- SKYTEMPLE-5E
- SKYTEMPLE-5F
- SKYTEMPLE-5G
- SKYTEMPLE-5J

**Comment by theCapypara** [comment]
@Adex-8x Can you send me the ssb file that caused the error?

**Comment by Adex-8x** [comment]
Sure, here it is: [title.ssb.zip](https://github.com/SkyTemple/skytemple-ssb-debugger/files/8343628/title.ssb.zip)

**Comment by Adex-8x** [comment]
@theCapypara I've consistently managed to replicate this error. Using `alias previous;` in any targeted routine, saving the script, and closing SkyTemple will make the script unable to be opened later on.

**Comment by theCapypara** [comment]
I'm unable to reproduce this. Can you post an example Explorerscript?

**Comment by Adex-8x** [comment]
[title.txt](https://github.com/SkyTemple/skytemple-ssb-debugger/files/8382974/title.txt)
