### ISSUE TITLE
Incorrect auto replacement or typo

### ISSUE THREAD

**Issue by mirkn** [SkyTemple/skytemple-ssb-debugger#76]
https://github.com/SkyTemple/skytemple-ssb-debugger/blob/3d25a62aa3bf19ef77c4d0b0b961d577cafc5624/skytemple_ssb_debugger/controller/script_editor.py#L608

https://github.com/SkyTemple/skytemple-ssb-debugger/blob/3d25a62aa3bf19ef77c4d0b0b961d577cafc5624/skytemple_ssb_debugger/controller/script_editor.py#L630

        search_down = not self.builder.get_object('sr_search_setting_search_backward2s').get_active()  #backward2s < backwards

Breaks "find and replace"     @theCapypara  ;-)

**Comment by theCapypara** [comment]
whoops.

**Comment by theCapypara** [comment]
This has been solved.
