### ISSUE TITLE
Improve debug printing

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/skytemple-ssb-debugger#83]
- Check what exactly DebugPrint2 was meant to be and fix up the offsets
- Support hooking into the copy of DebugPrint0 and into DebugPrintTrace

**Comment by Frostbyte0x70** [comment]
Some info that could be useful here:

SkyTemple has 2 sets of flags labelled "Debug Flags 1" and "Debug Flags 2". The debug menu of the game referes to these as "Debug Switch" and "Debug Log", respectively.

The Debug Log flags can be used to enable logging of certain additional debug messages. Some (or maybe even all of them) work in release ROMs. The internal names for the flags are:
- Dungeon
- Ground
- Script
- Script debug
- Script supervision
- Script command
- Sound
- BGM
- SE
- Flag
- File
- Memory
- Backup
- Thread
- Kernel
- Performance
