### ISSUE TITLE
Copy-pasting text crashes SkyTemple

### ISSUE THREAD

**Issue by Frostbyte0x70** [SkyTemple/skytemple-ssb-debugger#97]
Originally reported at: https://discord.com/channels/710190644152369162/712341699292037121/1109113298357583892

Trying to copy or paste text from the debugger script window causes a crash (full crash that closes the whole program, no errors are logged).

**Comment by theCapypara** [comment]
This is a memory corrpution issue in Gdk, most likely https://gitlab.gnome.org/GNOME/gtk/-/issues/5591

Although even with all GDK and GTK debugging enabled the crash is so hard for us, that we don't even get the error messages described in that issue.

**Comment by theCapypara** [comment]
I opened another upstream issue, since this actually seems to be slightly different to the error above:
https://gitlab.gnome.org/GNOME/gtk/-/issues/5843
